Importing the Dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import sklearn
import pickle
print("numpy",np.__version__)
print("pandas",pd.__version__)
print("sklearn",sklearn.__version__)

numpy 2.0.2
pandas 2.2.2
sklearn 1.6.1

In [ ]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
49605,44132,-1.211298,-0.450385,1.440502,0.354908,-0.408886,1.636777,-0.951234,1.185703,-1.020024,...,0.086607,0.526001,0.191522,-1.026321,-0.529712,-0.057442,0.125643,0.000680,79.00,0.0
49606,44132,1.176642,0.154754,0.246080,0.800814,-0.590838,-1.487705,0.336949,-0.316725,-0.047056,...,-0.008572,-0.105115,-0.017629,0.937907,0.463495,0.332980,-0.062039,0.016149,40.00,0.0
49607,44133,-1.103844,0.186527,1.568397,1.307678,0.316942,0.290415,1.147621,-0.222930,0.000022,...,-0.160645,0.468407,0.389831,0.213000,-0.015877,-0.278962,0.322504,-0.270168,108.00,0.0
49608,44134,-0.262018,0.851831,1.459865,1.057694,-0.725526,0.274325,1.750817,-1.097029,0.439934,...,-0.272138,0.032569,-0.141121,0.476174,-0.587678,0.288669,-0.914934,-0.676786,172.82,0.0
49609,44135,-4.719790,-4.249875,1.850000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49610 entries, 0 to 49609
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    49610 non-null  int64
 1   V1      49610 non-null  float64
 2   V2      49610 non-null  float64
 3   V3      49610 non-null  float64
 4   V4      49609 non-null  float64
 5   V5      49609 non-null  float64
 6   V6      49609 non-null  float64
 7   V7      49609 non-null  float64
 8   V8      49609 non-null  float64
 9   V9      49609 non-null  float64
 10  V10     49609 non-null  float64
 11  V11     49609 non-null  float64
 12  V12     49609 non-null  float64
 13  V13     49609 non-null  float64
 14  V14     49609 non-null  float64
 15  V15     49609 non-null  float64
 16  V16     49609 non-null  float64
 17  V17     49609 non-null  float64
 18  V18     49609 non-null  float64
 19  V19     49609 non-null  float64
 20  V20     49609 non-null  float64
 21  V21     49609 non-null  float64
 22  V22     49609 non-null  float64
 23  V23     49609 non-null  float64
 24  V24     49609 non-null  float64
 25  V25     49609 non-null  float64
 26  V26     49609 non-null  float64
 27  V27     49609 non-null  float64
 28  V28     49609 non-null  float64
 29  Amount  49609 non-null  float64
 30  Class   49609 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 11.7 MB

In [ ]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    49461
1.0      148
Name: count, dtype: int64

This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction

In [ ]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(49461, 31)
(148, 31)

In [ ]:
# statistical measures of the data
legit.Amount.describe()

count    49461.000000
mean        93.099593
std        253.325102
min          0.000000
25%          7.680000
50%         25.000000
75%         85.000000
max      12910.930000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     148.000000
mean      100.170676
std       233.347471
min         0.000000
25%         1.000000
50%         9.560000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,28809.010473,-0.220239,-0.003947,0.726173,0.167967,-0.240785,0.111250,-0.096470,0.042413,0.134593,...,0.046113,-0.031134,-0.106800,-0.039391,0.008275,0.135623,0.020410,0.003001,0.004455,93.099593
1.0,26877.182432,-7.675017,5.448919,-10.398242,5.939649,-5.681176,-2.280722,-8.068966,3.739332,-3.587074,...,0.470319,0.886835,-0.225326,-0.284732,-0.084733,0.246743,0.155479,0.603171,0.030658,100.170676

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [ ]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
16732,28095,-0.989989,1.471500,0.717310,-0.224895,0.191542,-0.448006,0.498008,0.160770,-0.633829,...,-0.045137,-0.399993,-0.125750,-0.430167,-0.228488,0.112902,-0.449389,0.056651,7.02,0.0
331,241,1.181572,0.241408,0.024537,0.885832,-0.121471,-0.275552,-0.142414,0.031283,0.253328,...,-0.143114,-0.172136,-0.156844,-0.045282,0.583795,0.412511,0.001454,0.030863,12.31,0.0
28863,35204,-0.599001,0.478255,1.497982,-0.341055,0.544681,-0.561233,0.926236,-0.263097,-0.899773,...,-0.008404,-0.030973,-0.277672,0.084140,0.261249,1.115779,-0.232207,-0.179081,38.90,0.0
12639,22150,-0.779440,0.373681,2.678701,-1.928857,0.090949,0.631897,0.232112,0.133500,2.170946,...,-0.041551,0.505745,-0.333557,-0.311913,0.313808,-0.803204,-0.048476,-0.167515,11.85,0.0
45350,42303,-1.373784,-0.080674,2.711809,1.347128,0.256678,-0.351185,-0.428362,0.200538,0.281153,...,-0.068448,-0.123802,-0.130061,0.403627,0.310352,-0.336794,-0.084476,0.267646,1.00,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
46909,42985,-4.075975,0.963031,-5.076070,4.955963,-0.161437,-2.832663,-7.619765,1.618895,-2.992092,...,1.030738,0.165328,-1.017502,-0.477983,-0.304987,-0.106089,1.899714,0.511462,1.00,1.0
46918,42988,-4.423508,1.648048,-6.934388,4.894601,-5.078131,0.010849,-3.409096,1.409291,-3.260672,...,0.698359,0.487478,1.228698,-0.535217,0.388278,-0.009466,2.300164,0.081231,648.00,1.0
46998,43028,-1.109646,0.811069,-1.138135,0.935265,-2.330248,-0.116106,-1.621986,0.458028,-0.912189,...,0.641594,0.841755,0.176728,0.081004,-0.258899,0.707654,0.418649,0.080756,204.27,1.0
47802,43369,-3.365319,2.426503,-3.752227,0.276017,-2.305870,-1.961578,-3.029283,-1.674462,0.183961,...,2.070008,-0.512626,-0.248502,0.126550,0.104166,-1.055997,-1.200165,-1.012066,88.00,1.0
48094,43494,-1.278138,0.716242,-1.143279,0.217805,-1.293890,-1.168952,-2.564182,0.204532,-1.611155,...,0.490183,0.470427,-0.126261,-0.126644,-0.661908,-0.349793,0.454851,0.137843,24.90,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0    148
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,28426.050813,-0.164968,0.055997,0.689458,0.150223,-0.266602,0.141232,-0.097954,0.026213,0.129687,...,0.040946,0.008356,-0.205022,0.004559,0.031585,0.131679,0.031968,0.007158,0.005378,89.967683
1.0,26877.182432,-7.675017,5.448919,-10.398242,5.939649,-5.681176,-2.280722,-8.068966,3.739332,-3.587074,...,0.470319,0.886835,-0.225326,-0.284732,-0.084733,0.246743,0.155479,0.603171,0.030658,100.170676

Splitting the data into Features & Targets

In [ ]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
16732  28095 -0.989989  1.471500  0.717310 -0.224895  0.191542 -0.448006
331      241  1.181572  0.241408  0.024537  0.885832 -0.121471 -0.275552
28863  35204 -0.599001  0.478255  1.497982 -0.341055  0.544681 -0.561233
12639  22150 -0.779440  0.373681  2.678701 -1.928857  0.090949  0.631897
45350  42303 -1.373784 -0.080674  2.711809  1.347128  0.256678 -0.351185
...      ...       ...       ...       ...       ...       ...       ...
46909  42985 -4.075975  0.963031 -5.076070  4.955963 -0.161437 -2.832663
46918  42988 -4.423508  1.648048 -6.934388  4.894601 -5.078131  0.010849
46998  43028 -1.109646  0.811069 -1.138135  0.935265 -2.330248 -0.116106
47802  43369 -3.365319  2.426503 -3.752227  0.276017 -2.305870 -1.961578
48094  43494 -1.278138  0.716242 -1.143279  0.217805 -1.293890 -1.168952

             V7        V8        V9  ...       V20       V21       V22  \
16732  0.498008  0.160770 -0.633829  ... -0.109346 -0.045137 -0.399993
331   -0.142414  0.031283  0.253328  ... -0.010394 -0.143114 -0.172136
28863  0.926236 -0.263097 -0.899773  ...  0.329497 -0.008404 -0.030973
12639  0.232112  0.133500  2.170946  ... -0.069104 -0.041551  0.505745
45350 -0.428362  0.200538  0.281153  ...  0.164346 -0.068448 -0.123802
...         ...       ...       ...  ...       ...       ...       ...
46909 -7.619765  1.618895 -2.992092  ...  0.058861  1.030738  0.165328
46918 -3.409096  1.409291 -3.260672  ... -0.562264  0.698359  0.487478
46998 -1.621986  0.458028 -0.912189  ...  0.168891  0.641594  0.841755
47802 -3.029283 -1.674462  0.183961  ... -0.036837  2.070008 -0.512626
48094 -2.564182  0.204532 -1.611155  ...  0.817203  0.490183  0.470427

            V23       V24       V25       V26       V27       V28  Amount
16732 -0.125750 -0.430167 -0.228488  0.112902 -0.449389  0.056651    7.02
331   -0.156844 -0.045282  0.583795  0.412511  0.001454  0.030863   12.31
28863 -0.277672  0.084140  0.261249  1.115779 -0.232207 -0.179081   38.90
12639 -0.333557 -0.311913  0.313808 -0.803204 -0.048476 -0.167515   11.85
45350 -0.130061  0.403627  0.310352 -0.336794 -0.084476  0.267646    1.00
...         ...       ...       ...       ...       ...       ...     ...
46909 -1.017502 -0.477983 -0.304987 -0.106089  1.899714  0.511462    1.00
46918  1.228698 -0.535217  0.388278 -0.009466  2.300164  0.081231  648.00
46998  0.176728  0.081004 -0.258899  0.707654  0.418649  0.080756  204.27
47802 -0.248502  0.126550  0.104166 -1.055997 -1.200165 -1.012066   88.00
48094 -0.126261 -0.126644 -0.661908 -0.349793  0.454851  0.137843   24.90

[640 rows x 30 columns]

In [ ]:
print(Y)

16732    0.0
331      0.0
28863    0.0
12639    0.0
45350    0.0
        ...
46909    1.0
46918    1.0
46998    1.0
47802    1.0
48094    1.0
Name: Class, Length: 640, dtype: float64

Split the data into Training data & Testing Data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(640, 30) (512, 30) (128, 30)

Model Training

Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.982421875

In [ ]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.96875

In [ ]:
# with open('model.pkl','wb') as file:
#   pickle.dump(model, file)

In [ ]:
import pandas as pd

new_transaction = pd.DataFrame({
    'Time': [1000],
    'V1': [-1.35],
    'V2': [0.45],
    'V3': [1.23],
    'V4': [-0.56],
    'V5': [0.12],
    'V6': [-0.98],
    'V7': [0.34],
    'V8': [0.11],
    'V9': [-0.75],
    'V10': [0.67],
    'V11': [1.25],
    'V12': [-0.45],
    'V13': [0.89],
    'V14': [-1.56],
    'V15': [0.23],
    'V16': [-0.78],
    'V17': [0.56],
    'V18': [0.91],
    'V19': [-0.22],
    'V20': [0.05],
    'V21': [-0.14],
    'V22': [0.88],
    'V23': [-0.09],
    'V24': [0.34],
    'V25': [-0.12],
    'V26': [0.45],
    'V27': [0.03],
    'V28': [-0.02],
    'Amount': [250.75]
})

prediction = model.predict(new_transaction)

if prediction[0] == 1:
    print("🚨 Fraud Transaction")
else:
    print("✅ Legit Transaction")

✅ Legit Transaction